return {
    "nvim-treesitter/nvim-treesitter",
    branch = 'master',
    lazy = false,
    build = ":TSUpdate",
    dependencies = {
        "nvim-treesitter/nvim-treesitter-textobjects",
    },
    config = function()
        require("nvim-treesitter.configs").setup({
            ensure_installed = { "c", "lua", "vim", "vimdoc", "query", "markdown", "markdown_inline" },
            auto_install = true,
            indent = { enable = true },
            highlight = { enable = true },
            incremental_selection = {
                enable = true,
                keymaps = {
                    init_selection = '<leader>ss',
                    node_incremental = '<leader>si',
                    scope_incremental = '<leader>sc',
                    node_decremental = '<leader>sd',
                },
            },

            autotag = { enable = true },
            textobjects = {
                select = {
                    enable = true,
                    -- Automatically jump forward to textobj, similar to targets.vim 
                    lookahead = true,
                    keymaps = {
                        ["fn"] = "@foo.outer",
                        -- assignment == equal
                        ["ie"] = "@assignment.inner",
                        ["el"] = "@assignment.lhs",
                        ["ae"] = "@assignment.outer",
                        ["er"] = "@assignment.rhs",
                        ["ia"] = "@attribute.inner",
                        ["aa"] = "@attribute.outer",
                        ["ik"] = "@block.inner",
                        ["ak"] = "@block.outer",
                        ["ic"] = "@call.inner",
                        ["ac"] = "@call.outer",
                        -- class ~= struct
                        ["is"] = "@class.inner",
                        ["as"] = "@class.outer",
                        ["i/"] = "@comment.inner",
                        ["a/"] = "@comment.outer",
                        -- conditionnal == if
                        ["ii"] = "@conditional.inner",
                        ["ai"] = "@conditional.outer",
                        ["ig"] = "@frame.inner",
                        ["ag"] = "@frame.outer",
                        ["if"] = "@function.inner",
                        ["af"] = "@function.outer",
                        ["il"] = "@loop.inner",
                        ["al"] = "@loop.outer",
                        ["an"] = "@number.inner",
                        ["ip"] = "@parameter.inner",
                        ["ap"] = "@parameter.outer",
                        ["ix"] = "@regex.inner",
                        ["ax"] = "@regex.outer",
                        ["ir"] = "@return.inner",
                        ["ar"] = "@return.outer",
                        -- scope == orbit
                        ["io"] = "@scopename.inner",
                        -- statement ~= quote
                        ["aq"] = "@statement.outer",
                    },
                    ['@parameter.outer'] = 'v', -- charwise
                    ['@function.outer'] = 'v', -- linewise
                    ['@class.outer'] = '<c-v>', -- blockwise
                },
                move = {
                    enable = true,
                    set_jumps = true, -- whether to set jumps in the jumplist
                    goto_next_start = {
                        ["tie"] = "@assignment.inner",
                        ["tel"] = "@assignment.lhs",
                        ["tae"] = "@assignment.outer",
                        ["ter"] = "@assignment.rhs",
                        ["tia"] = "@attribute.inner",
                        ["taa"] = "@attribute.outer",
                        ["tik"] = "@block.inner",
                        ["tak"] = "@block.outer",
                        ["tic"] = "@call.inner",
                        ["tac"] = "@call.outer",
                        ["tis"] = "@class.inner",
                        ["tas"] = "@class.outer",
                        ["ti/"] = "@comment.inner",
                        ["ta/"] = "@comment.outer",
                        ["tii"] = "@conditional.inner",
                        ["tai"] = "@conditional.outer",
                        ["tig"] = "@frame.inner",
                        ["tag"] = "@frame.outer",
                        ["tif"] = "@function.inner",
                        ["taf"] = "@function.outer",
                        ["til"] = "@loop.inner",
                        ["tal"] = "@loop.outer",
                        ["tan"] = "@number.inner",
                        ["tip"] = "@parameter.inner",
                        ["tap"] = "@parameter.outer",
                        ["tix"] = "@regex.inner",
                        ["tax"] = "@regex.outer",
                        ["tir"] = "@return.inner",
                        ["tar"] = "@return.outer",
                        ["tio"] = "@scopename.inner",
                        ["taq"] = "@statement.outer",
                    },
                    goto_next_end = {
                        ["efn"] = "@foo.outer",
                        ["eie"] = "@assignment.inner",
                        ["eel"] = "@assignment.lhs",
                        ["eae"] = "@assignment.outer",
                        ["eer"] = "@assignment.rhs",
                        ["eia"] = "@attribute.inner",
                        ["eaa"] = "@attribute.outer",
                        ["eik"] = "@block.inner",
                        ["eak"] = "@block.outer",
                        ["eic"] = "@call.inner",
                        ["eac"] = "@call.outer",
                        ["eis"] = "@class.inner",
                        ["eas"] = "@class.outer",
                        ["ei/"] = "@comment.inner",
                        ["ea/"] = "@comment.outer",
                        ["eii"] = "@conditional.inner",
                        ["eai"] = "@conditional.outer",
                        ["eig"] = "@frame.inner",
                        ["eag"] = "@frame.outer",
                        ["eif"] = "@function.inner",
                        ["eaf"] = "@function.outer",
                        ["eil"] = "@loop.inner",
                        ["eal"] = "@loop.outer",
                        ["ean"] = "@number.inner",
                        ["eip"] = "@parameter.inner",
                        ["eap"] = "@parameter.outer",
                        ["eix"] = "@regex.inner",
                        ["eax"] = "@regex.outer",
                        ["eir"] = "@return.inner",
                        ["ear"] = "@return.outer",
                        ["eio"] = "@scopename.inner",
                        ["eaq"] = "@statement.outer",
                    },
                    goto_previous_start = {
                        ["Tie"] = "@assignment.inner",
                        ["Tel"] = "@assignment.lhs",
                        ["Tae"] = "@assignment.outer",
                        ["Ter"] = "@assignment.rhs",
                        ["Tia"] = "@attribute.inner",
                        ["Taa"] = "@attribute.outer",
                        ["Tik"] = "@block.inner",
                        ["Tak"] = "@block.outer",
                        ["Tic"] = "@call.inner",
                        ["Tac"] = "@call.outer",
                        ["Tis"] = "@class.inner",
                        ["Tas"] = "@class.outer",
                        ["Ti/"] = "@comment.inner",
                        ["Ta/"] = "@comment.outer",
                        ["Tii"] = "@conditional.inner",
                        ["Tai"] = "@conditional.outer",
                        ["Tig"] = "@frame.inner",
                        ["Tag"] = "@frame.outer",
                        ["Tif"] = "@function.inner",
                        ["Taf"] = "@function.outer",
                        ["Til"] = "@loop.inner",
                        ["Tal"] = "@loop.outer",
                        ["Tan"] = "@number.inner",
                        ["Tip"] = "@parameter.inner",
                        ["Tap"] = "@parameter.outer",
                        ["Tix"] = "@regex.inner",
                        ["Tax"] = "@regex.outer",
                        ["Tir"] = "@return.inner",
                        ["Tar"] = "@return.outer",
                        ["Tio"] = "@scopename.inner",
                        ["Taq"] = "@statement.outer",
                    },
                    goto_previous_end = {
                        ["Eie"] = "@assignment.inner",
                        ["Eel"] = "@assignment.lhs",
                        ["Eae"] = "@assignment.outer",
                        ["Eer"] = "@assignment.rhs",
                        ["Eia"] = "@attribute.inner",
                        ["Eaa"] = "@attribute.outer",
                        ["Eik"] = "@block.inner",
                        ["Eak"] = "@block.outer",
                        ["Eic"] = "@call.inner",
                        ["Eac"] = "@call.outer",
                        ["Eis"] = "@class.inner",
                        ["Eas"] = "@class.outer",
                        ["Ei/"] = "@comment.inner",
                        ["Ea/"] = "@comment.outer",
                        ["Eii"] = "@conditional.inner",
                        ["Eai"] = "@conditional.outer",
                        ["Eig"] = "@frame.inner",
                        ["Eag"] = "@frame.outer",
                        ["Eif"] = "@function.inner",
                        ["Eaf"] = "@function.outer",
                        ["Eil"] = "@loop.inner",
                        ["Eal"] = "@loop.outer",
                        ["Ean"] = "@number.inner",
                        ["Eip"] = "@parameter.inner",
                        ["Eap"] = "@parameter.outer",
                        ["Eix"] = "@regex.inner",
                        ["Eax"] = "@regex.outer",
                        ["Eir"] = "@return.inner",
                        ["Ear"] = "@return.outer",
                        ["Eio"] = "@scopename.inner",
                        ["Eaq"] = "@statement.outer",
                    },
                    goto_next = {
                        -- ["]ie"] = "@assignment.inner",
                        -- ["]el"] = "@assignment.lhs",
                        -- ["]ae"] = "@assignment.outer",
                        -- ["]er"] = "@assignment.rhs",
                        -- ["]ia"] = "@attribute.inner",
                        -- ["]aa"] = "@attribute.outer",
                        -- ["]ik"] = "@block.inner",
                        -- ["]ak"] = "@block.outer",
                        -- ["]ic"] = "@call.inner",
                        -- ["]ac"] = "@call.outer",
                        -- ["]is"] = "@class.inner",
                        -- ["]as"] = "@class.outer",
                        -- ["]i/"] = "@comment.inner",
                        -- ["]a/"] = "@comment.outer",
                        -- ["]ii"] = "@conditional.inner",
                        -- ["]ai"] = "@conditional.outer",
                        -- ["]ig"] = "@frame.inner",
                        -- ["]ag"] = "@frame.outer",
                        -- ["]if"] = "@function.inner",
                        -- ["]af"] = "@function.outer",
                        -- ["]il"] = "@loop.inner",
                        -- ["]al"] = "@loop.outer",
                        -- ["]an"] = "@number.inner",
                        -- ["]ip"] = "@parameter.inner",
                        -- ["]ap"] = "@parameter.outer",
                        -- ["]ix"] = "@regex.inner",
                        -- ["]ax"] = "@regex.outer",
                        -- ["]ir"] = "@return.inner",
                        -- ["]ar"] = "@return.outer",
                        -- ["]io"] = "@scopename.inner",
                        -- ["]aq"] = "@statement.outer",
                    },
                    goto_previous = {
                        -- ["[ie"] = "@assignment.inner",
                        -- ["[el"] = "@assignment.lhs",
                        -- ["[ae"] = "@assignment.outer",
                        -- ["[er"] = "@assignment.rhs",
                        -- ["[ia"] = "@attribute.inner",
                        -- ["[aa"] = "@attribute.outer",
                        -- ["[ik"] = "@block.inner",
                        -- ["[ak"] = "@block.outer",
                        -- ["[ic"] = "@call.inner",
                        -- ["[ac"] = "@call.outer",
                        -- ["[is"] = "@class.inner",
                        -- ["[as"] = "@class.outer",
                        -- ["[i/"] = "@comment.inner",
                        -- ["[a/"] = "@comment.outer",
                        -- ["[ii"] = "@conditional.inner",
                        -- ["[ai"] = "@conditional.outer",
                        -- ["[ig"] = "@frame.inner",
                        -- ["[ag"] = "@frame.outer",
                        -- ["[if"] = "@function.inner",
                        -- ["[af"] = "@function.outer",
                        -- ["[il"] = "@loop.inner",
                        -- ["[al"] = "@loop.outer",
                        -- ["[an"] = "@number.inner",
                        -- ["[ip"] = "@parameter.inner",
                        -- ["[ap"] = "@parameter.outer",
                        -- ["[ix"] = "@regex.inner",
                        -- ["[ax"] = "@regex.outer",
                        -- ["[ir"] = "@return.inner",
                        -- ["[ar"] = "@return.outer",
                        -- ["[io"] = "@scopename.inner",
                        -- ["[aq"] = "@statement.outer",
                    },
                },
                swap = {
                    enable = true,
                    swap_next = {
                        ["<leader>a"] = "@parameter.inner",
                    },
                    swap_previous = {
                        ["<leader>A"] = "@parameter.inner",
                    },
                },
                lsp_interop = {
                    enable = true,
                    border = 'none',
                    floating_preview_opts = {},
                    peek_definition_code = {
                        ["<leader>df"] = "@function.outer",
                        ["<leader>dF"] = "@class.outer",
                    },
                },
            },
        })
        local ts_repeat_move = require "nvim-treesitter.textobjects.repeatable_move"

        -- Repeat movement with ; and ,
        -- ensure ; goes forward and , goes backward regardless of the last direction
        vim.keymap.set({ "n", "x", "o" }, ";", ts_repeat_move.repeat_last_move_next)
        vim.keymap.set({ "n", "x", "o" }, ",,", ts_repeat_move.repeat_last_move_previous)

        -- Optionally, make builtin f, F, t, T also repeatable with ; and ,
        vim.keymap.set({ "n", "x", "o" }, "f", ts_repeat_move.builtin_f_expr, { expr = true })
        vim.keymap.set({ "n", "x", "o" }, "F", ts_repeat_move.builtin_F_expr, { expr = true })
        vim.keymap.set({ "n", "x", "o" }, "t", ts_repeat_move.builtin_t_expr, { expr = true })
        vim.keymap.set({ "n", "x", "o" }, "T", ts_repeat_move.builtin_T_expr, { expr = true })

        vim.keymap.set("n", "gd", function () vim.api.nvim_input("]ac") vim.defer_fn(function() require("fzf-lua").lsp_definitions() end, 10)  end, { desc = "Go to definition" })
        vim.keymap.set("n", "gs", function () require("fzf-lua").lsp_definitions() end, { desc = "Go to definition" })
    end,
}
